#!/bin/bash
: 'Write a shell script named 0-current_working_directory that prints the absolute path name of the current working directory.
Example:
➜ ./0-current_working_directory
/Users/devops/project/whereami
➜
'
current_working_directory=$(pwd)
echo $current_working_directory
