#!/bin/bash 

: '
Write a shell script that prints the current environment variables which name starts with TERM.

➜ ./6-env-pipe-filter
TERM=xterm-256color
TERM_PROGRAM_VERSION=440
TERM_SESSION_ID=13E875F2-7C1F-4AB1-8B49-47F229B78CCA
'
vars=(${!TERM*})
size=$((${#vars[@]} - 1))

vals=()

for var in ${vars[@]}
do
    vals+=($(eval $(echo echo \$$var)))
done

for i in `seq 0 $size`
do
    echo ${vars[i]}=${vals[i]}
done
